### ISSUE TITLE
nice paper，please could u provide the pre-train model？

### ISSUE THREAD

**Issue by eezhang123** [yzxing87/Invertible-ISP#2]

**Comment by yzxing87** [comment]
Hi, thanks for the interest.

**Comment by yzxing87** [comment]
Hi, thanks for raising the issue. 

We didn't provide the pretrained model since in the context of ISP, one trained model can only be applied for a specific camera. This is due to the camera-dependent proprietary raw color space and photo-finishing steps. We may offer our pretrained model as a reference recently.

**Comment by yzxing87** [comment]
We have uploaded our [pretrained weights](https://github.com/yzxing87/Invertible-ISP/tree/main/pretrained). Thanks.
