### ISSUE TITLE
Step of demosaicing

### ISSUE THREAD

**Issue by xunmeibuyue** [yzxing87/Invertible-ISP#9]
Hi Yazhou,

An excellent work!

I notice that you use bilinear demosaicing by Python library `colour_demosaicing`, and I guess it is aiming to reverse this step. However, I wonder would if bilinear demosaicing would be enough for an ISP? It seems to have some disadvantages, such as colour error and blurring. Did you notice this problem?

Best,
Kenneth

**Comment by yzxing87** [comment]
Hi Kenneth,

Yes, we use bilinear demosaicing since it is invertible. And I admit that bilinear demosaicing is so simple that it may not fit for some advanced ISPs. But in our method, our model can optimize the output RGB towards the ground truth, whose demosaicing is more complicated that bilinear demosaicing. So it should not be a problem in our pipeline. 

Actually we found there is a bug in ``colour_demosaicing``, which may cause the color error for the RGB output. And we should note that the results in our paper are correct (after fixing the bug). We may post the fixing method in readme.

**Comment by xunmeibuyue** [comment]
Get it.

And maybe you could create a pull request to `colour_demosaicing`? That would be a meaningful contribution~

Anyway, thanks!

**Comment by yzxing87** [comment]
Thanks, Kenneth. Will do.
